"""
AI attack analysis using Google Gemini.

WHEN CALLED: Only for confirmed suspicious activity.
Not every request. Not every fingerprint. Only when
the background worker creates a new attack session.

WHY AI HERE: Pattern detection tells us WHAT type of
attack. AI tells us WHY it's happening and WHAT TO DO
about it — in plain English for the dashboard.

FALLBACK: Deterministic templates when AI is unavailable.
The system works perfectly without AI. AI just adds
human-readable explanations.
"""

import json

from Vigil.config import settings, logger


async def analyze_attack(
    attack_type: str,
    fingerprint_data: dict,
    request_samples: list[dict],
    detection_evidence: list[str],
) -> dict:
    """
    Generate an AI analysis of a detected attack.

    Returns a structured dict with:
    - attack_type, confidence, severity
    - evidence_summary
    - recommended_action
    - explanation (human-readable)
    """
    if not settings.gemini_api_key:
        return _fallback_analysis(
            attack_type, detection_evidence
        )

    try:
        import google.generativeai as genai

        genai.configure(api_key=settings.gemini_api_key)

        prompt = f"""You are a cybersecurity analyst.
Analyze this detected API attack.

DETECTED ATTACK TYPE: {attack_type}

FINGERPRINT DATA:
{json.dumps(fingerprint_data, indent=2)}

SAMPLE REQUESTS (last 20):
{json.dumps(request_samples[:20], indent=2)}

DETECTION EVIDENCE:
{json.dumps(detection_evidence, indent=2)}

Respond in this exact JSON format:
{{
    "attack_type": "the specific attack type",
    "confidence": 0.0 to 1.0,
    "severity": "critical|high|medium|low",
    "evidence_summary": ["point 1", "point 2"],
    "recommended_action": "block|throttle|monitor",
    "explanation": "2-3 sentence explanation",
    "technical_details": "technical explanation"
}}"""

        model = genai.GenerativeModel("gemini-1.5-flash")
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                temperature=0.1,
            ),
        )
        return json.loads(response.text)

    except Exception as e:
        logger.error(
            "AI analysis failed, using fallback",
            extra={
                "error": str(e),
                "attack_type": attack_type,
            },
        )
        return _fallback_analysis(
            attack_type, detection_evidence
        )


def _fallback_analysis(
    attack_type: str,
    evidence: list[str],
) -> dict:
    """
    Deterministic fallback when AI is unavailable.

    Returns the same structured format as the AI would,
    ensuring the dashboard always has something to display.
    """
    severity_map = {
        "credential_stuffing": "high",
        "enumeration": "medium",
        "scraping": "medium",
        "ddos": "critical",
    }
    explanation_map = {
        "credential_stuffing": (
            "Multiple login attempts with different "
            "credentials detected, suggesting automated "
            "credential stuffing from a breached database."
        ),
        "enumeration": (
            "Sequential access to numbered resources "
            "detected, suggesting automated resource "
            "discovery or data scraping."
        ),
    }

    return {
        "attack_type": attack_type,
        "confidence": 0.7,
        "severity": severity_map.get(
            attack_type, "medium"
        ),
        "evidence_summary": evidence[:5],
        "recommended_action": "block",
        "explanation": explanation_map.get(
            attack_type,
            f"Suspicious {attack_type} pattern detected "
            f"by automated analysis.",
        ),
        "technical_details": (
            "Analysis generated by deterministic fallback "
            "system (AI unavailable)."
        ),
    }