"""initial_schema

Revision ID: 77c6156b3311
Revises: 
Create Date: 2026-03-15 21:55:06.965538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77c6156b3311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_blocked', sa.Integer(), nullable=False),
    sa.Column('distinct_ip_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_allowlisted', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fingerprints_fingerprint_hash'), 'fingerprints', ['fingerprint_hash'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('max_requests_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('action_taken', sa.String(length=20), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('body_hash', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_requests_fp_time', 'requests', ['fingerprint_hash', 'created_at'], unique=False)
    op.create_index('idx_requests_org_time', 'requests', ['org_id', 'created_at'], unique=False)
    op.create_index('idx_requests_suspicious', 'requests', ['is_suspicious', 'created_at'], unique=False, postgresql_where=sa.text('is_suspicious = true'))
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_fingerprint_hash'), 'requests', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_requests_org_id'), 'requests', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('attack_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=16), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_fingerprints', sa.Integer(), nullable=False),
    sa.Column('total_ips', sa.Integer(), nullable=False),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_sessions_fingerprint_hash'), 'attack_sessions', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_attack_sessions_org_id'), 'attack_sessions', ['org_id'], unique=False)
    op.create_table('fingerprint_ips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fingerprint_id'], ['fingerprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fp_ips_unique', 'fingerprint_ips', ['fingerprint_id', 'ip_address'], unique=True)
    op.create_index(op.f('ix_fingerprint_ips_fingerprint_id'), 'fingerprint_ips', ['fingerprint_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=16), nullable=True),
    sa.Column('attack_session_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attack_session_id'], ['attack_sessions.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_index(op.f('ix_fingerprint_ips_fingerprint_id'), table_name='fingerprint_ips')
    op.drop_index('idx_fp_ips_unique', table_name='fingerprint_ips')
    op.drop_table('fingerprint_ips')
    op.drop_index(op.f('ix_attack_sessions_org_id'), table_name='attack_sessions')
    op.drop_index(op.f('ix_attack_sessions_fingerprint_hash'), table_name='attack_sessions')
    op.drop_table('attack_sessions')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_requests_org_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_fingerprint_hash'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_index('idx_requests_suspicious', table_name='requests', postgresql_where=sa.text('is_suspicious = true'))
    op.drop_index('idx_requests_org_time', table_name='requests')
    op.drop_index('idx_requests_fp_time', table_name='requests')
    op.drop_table('requests')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_fingerprints_fingerprint_hash'), table_name='fingerprints')
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
